AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Invokes webhooks in response to CodeBuild state changes (uksb-1q5j83kkh)

Parameters:
  SSMKeyId:
    Description: Key used to encrypt SSM parameters
    Type: String
    Default: alias/aws/ssm
  SSMPrefix:
    Description: Prefix used for SSM parameters
    Type: String
    Default: webhooks

Resources:
  WebhookInvoker:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.lambda_handler
      Runtime: python3.7
      AutoPublishAlias: live 
      CodeUri: ./lambdas/
      Events:
        BuildEvent:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - "aws.codebuild"
              detail-type:
                - "CodeBuild Build State Change"
      Environment:
        Variables:
          TABLE_NAME: !Ref HooksTable
      Policies:
        - KMSDecryptPolicy:
            KeyId: !Ref SSMKeyId
        - DynamoDBCrudPolicy:
            TableName: !Ref HooksTable
        - Statement:
            - Action: "ssm:GetParameter"
              Effect: "Allow"
              Resource: !Sub "arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${SSMPrefix}/*"

  HooksTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: CodeBuildWebhooks
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions: 
        - 
          AttributeName: "project"
          AttributeType: "S"
        - 
          AttributeName: "hook_url_param_name"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "project"
          KeyType: "HASH"
        - 
          AttributeName: "hook_url_param_name"
          KeyType: "RANGE"

Outputs:
  HooksTable:
    Description: DDB table used to register CodeBuild webhooks
    Value: !Ref HooksTable
